package com.depromeet.threedays.domain.key

const val RESOURCE_CREATE = "resource.created"
const val HABIT_CONSTRAINTS_INSUFFICIENT_DAY_OF_WEEKS = "habit.constraints.insufficient.day.of.weeks"
const val HABIT_ACHIEVEMENT_CONSTRAINTS_DATE_IS_IN_THE_PAST = "habit.achievement.constraints.date.is.in.the.past"
const val HABIT_ACHIEVEMENT_CONSTRAINTS_INVALID_ACHIEVEMENT_DATE = "habit.achievement.constraints.invalid.achievement.date"
const val HABIT_ACHIEVEMENT_CONSTRAINTS_INVALID_HABIT = "habit.achievement.constraints.invalid.habit"
const val HABIT_CONSTRAINTS_INSUFFICIENT_NOTIFICATION = "habit.constraints.insufficient.notification"
const val HABIT_NOT_FOUNT = "habit.not.found"
const val MEMBER_CONSTRAINTS_INVALID_MEMBER = "member.constraints.invalid.member"
const val MEMBER_NOT_FOUND = "member.not.found"
const val SOCIAL_LOGIN_ERROR = "social.login.error"
const val TOKEN_NOT_VALID = "token.not.valid"
const val ACCESS_DENIED_EXCEPTION = "AccessDeniedException"
const val INSUFFICIENT_AUTHENTICATION_EXCEPTION = "InsufficientAuthenticationException"
const val MATE_CONSTRAINTS_ALREADY_EXIST_MATE = "mate.constraints.already.exist.mate"
const val MATE_NOT_FOUNT = "mate.not.found"
const val CLIENT_NOT_FOUND = "client.not.found"
const val MATE_CONSTRAINTS_INVALID_HABIT = "mate.constraints.invalid.habit"
const val METHOD_ARGUMENT_NOT_VALID_EXCEPTION_BIND_EXCEPTION = "MethodArgumentNotValidException, BindException"
const val BAD_REQUEST = "BAD_REQUEST"
const val NO_INTERNET_CONNECTION ="No internet connection"
const val UNKNOWN_ERROR = "UNKNOWN_ERROR"
