name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: Deploy debug app to firebase app distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - run: echo $DEBUG_KEYSTORE_FILE | base64 -d > debug.keystore
      - run: ls -al
      - name: Build
        run: chmod +x ./gradlew && ./gradlew :app::assembleAlpha --quiet
        env:
          DEBUG_STORE_PASSWORD: ${{ secrets.DEBUG_STORE_PASSWORD }}
          DEBUG_KEY_PASSWORD: ${{ secrets.DEBUG_KEY_PASSWORD }}
          DEBUG_KEY_ALIAS: ${{ secrets.DEBUG_KEY_ALIAS }}
      - name: Fetch credential file from secrets
        uses: timheuer/base64-to-file@v1.2
        with:
          encodedString: ${{ secrets.FIREBASE_CREDENTIAL_FILE }}
          fileName: 'credential_file.json'
      - name: Upload artifact to Firebase Distribution using credential file
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.5
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          serviceCredentialsFile: credential_file.json
          groups: android
          file: app/build/outputs/apk/debug/app-debug.apk
          debug: true
